# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base

diffuser:
  so3:
    exp_rate: 10  # TODO: set this in py files

inference:
  name: null
  gpu_id: null  # CUDA GPU to use
  seed: 123

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN/
  output_dir: ./unconditional_inference_outputs/use_sde${inference.samples.use_sde}-exp_rate${diffuser.so3.exp_rate}/

  # Path to model weights.
  weights_path: ./weights/best_weights.pth

  diffusion:
    # Number of steps.
    num_t: 500
    # Analogous to sampling temperature.
    noise_scale: 0.1
    # Final t.
    min_t: 0.01

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 100
    # Maximum sequence length to sample.
    max_length: 500
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 5
    
    # use sde or ode to sample
    use_sde: False  # TODO: check this
